# Generated by Django 4.1 on 2022-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('post_id', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=10000)),
                ('tags', models.CharField(max_length=200)),
                ('post_img', models.ImageField(upload_to='')),
                ('table_connect', models.CharField(max_length=200)),
            ],
        ),
    ]
